---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: nfs-node-1
    box: generic/rocky9
    memory: 1024
    cpus: 1
    groups:
      - nfs
    interfaces:
      - network_name: private_network
        ip: 172.16.7.1

  - name: nfs-node-2
    box: generic/rocky9
    memory: 1024
    cpus: 1
    groups:
      - nfs
    interfaces:
      - network_name: private_network
        ip: 172.16.7.2

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      nfs:
        cluster_name: test-nfs-cluster
        hacluster_password: TestPassword123
        vip_ip: 172.16.7.7
        vip_cidr: 24
        vip_interface: eth1
        firewall_services:
          - high-availability
          - nfs
          - mountd
          - rpc-bind

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy