---
- name: Install HA required packages (Ubuntu)
  ansible.builtin.apt:
    name:
      - pcs
      - pacemaker
      - corosync
    state: present
    update_cache: yes
  register: apt_install

- name: move corosync.conf if installed
  ansible.builtin.command: mv /etc/corosync/corosync.conf /etc/corosync/corosync.conf.example
  args:
    removes: /etc/corosync/corosync.conf
    creates: /etc/corosync/corosync.conf.example
  when: apt_install.changed