---
- name: check if firewalld running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

- name: configure firewall
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ firewall_services }}"