---
- name: include os-specific package installation
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Enable and start pcsd service
  ansible.builtin.systemd:
    name: pcsd
    state: started
    enabled: yes

- name: include configure firewall
  ansible.builtin.include_tasks: "firewall.yml"
  when: configure_firewall | bool

- name: Set password for hacluster user
  ansible.builtin.user:
    name: hacluster
    password: "{{ hacluster_password | password_hash('sha512') }}"
